### PR TITLE
Mobile fixes

### LINKED ISSUE #893: Pinch to zoom feature on Android browsers
### Description

Hello, I found a small issue (or lack of a feature). The pinch to zoom in/out feature is unavailable on RapID v2 on mobile browsers but it's still available on v1. Please add this feature on v2 since some of us still use smartphones to edit.

### LINKED ISSUE #1353: 2 finger pinch/expand to zoom doesn't work in iOS Safari
### Description

On iPads, trying to zoom with 2 fingers pans the map instead of zooming. iD correctly zooms the map

### Screenshots

_No response_

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Safari 17.1

### The OS you're using

iPad OS 17.1

### Steps to reproduce

1. Go to Rapid
2. Pinch or expand with 2 fingers
3. Map pans instead of zooming

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.00/42.71980/-85.91276

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

_No response_

### PR DESCRIPTION
**Pull request by tannerwuster**
giphy com-media-8Bkr9UJQTuqEnzkOae-giphy
### Changes Made:
- Implemented pinch-to-zoom functionality for mobile browsers 
- Ensured compatibility and smooth functionality across different mobile devices. (Tested on iPad, iPhone and Android) 

closes #1353 and closes #893

### CODE REVIEW

File: modules/util/detect.js [hunk 1]
```diff
@@ -77,8 +77,8 @@ export function utilDetect(refresh) {
 
   _detected.isMobileWebKit = (/\b(iPad|iPhone|iPod)\b/.test(ua) ||
```
Comment (bhousel) [inline modules/util/detect.js:78]: Hah I didn't know this was in here.. It looks like we're not actually using this code - the `isMobileWebkit` flag is commented out in `UISystem.js`, so maybe best to remove the whole thing?

If I remember correctly, it was because Safari supports special `Gesture` events that no other browser supports?  UiSystem attempt(ed?) to cancel those events, but it could do that same thing without the `isMobileWebkit` flag. 🤔

Comment (tannerwuster) [reply modules/util/detect.js:78]: Thanks for catching that! You're right, the _detected.isMobileWebKit flag isn't being used in UISystem.js so I’ll just remove it.

**Comment by tannerwuster** [comment]
**A couple of things I'm trying to fix:**

**Before edit: zooming works**

https://github.com/facebook/Rapid/assets/49957271/84fda4a7-546c-49b6-aa3e-91aa942b370f

**After edit: pan becomes zoom and pinch to zoom doesn't register**

https://github.com/facebook/Rapid/assets/49957271/fc6ae991-72ac-4615-906e-03e2fa38c56b

It's weird that when I make an edit it adds an extra `this.activeTouches` point 🤔

File: modules/behaviors/MapInteractionBehavior.js [hunk 2]
```diff
@@ -362,4 +432,55 @@ export class MapInteractionBehavior extends AbstractBehavior {
...
+    if (now - this.lastZoomUpdate < 50) return;
+    this.lastZoomUpdate = now;
+
+    const viewport = this.context.viewport;
+    const currentZoom = viewport.transform.zoom;
+    const targetZoom = currentZoom * Math.log2(scaleChange + 1);
+
+    const clampedZoom = Math.max(MIN_Z, Math.min(targetZoom, MAX_Z));
+
+    requestAnimationFrame(() => {
```
Comment (bhousel) [inline modules/behaviors/MapInteractionBehavior.js:482]: You won't want to do this in `requestAnimationFrame` callback - the `PixiRenderer.js` code already will defer changes to the map transform, so you can just call `map.zoom(val)` directly.  (By deferring it this way, you can create a race condition where different changes to the transform are fighting with each other).

File: modules/behaviors/MapInteractionBehavior.js [hunk 3]
```diff
@@ -362,4 +432,55 @@ export class MapInteractionBehavior extends AbstractBehavior {
...
+            const scaleChange = currentDistance / this._initialPinchDistance;
+            const currentZoom = this.context.viewport.transform.zoom;
+
+            // Only apply changes if the scale change is significant
+            if (Math.abs(scaleChange - 1) > 0.01) {  // Adjust this threshold as needed
+                const baseDamping = 0.65;
+                const dampingFactor = currentZoom > 16 ? 0.25 : (currentZoom / 16) * baseDamping + 0.25;
+                const adjustedScaleChange = 1 + (scaleChange - 1) * dampingFactor;
+
+                this._applyPinchZoom(adjustedScaleChange);
```
Comment (bhousel) [inline modules/behaviors/MapInteractionBehavior.js:456]: yeah, thinking more about this, I think it's probably safe to just get rid of `this._applyPinchZoom` and at this point just call `map.zoom(newZoom)`. Transform changes are already throttled by the renderer.

**Comment by tannerwuster** [comment]
**Zoom** is now zippy! Adjusting the speed is my next step and also getting it to work when we edit the map.

https://github.com/facebook/Rapid/assets/49957271/c03885b1-7abe-49f0-a8ac-bd645836d081

**Comment by bhousel** [comment]
This looks great!! Thanks for your work on this 👍 
Let's merge it and try it out  🚀
